export const fontOptions = [
  { value: 'Arial, sans-serif', label: 'Arial' },
  { value: 'Arial Black, sans-serif', label: 'Arial Black' },
  { value: 'Comic Sans MS, sans-serif', label: 'Comic Sans MS' },
  { value: 'Courier New, monospace', label: 'Courier New' },
  { value: 'Didot eText W01 Italic', label: 'Didot eText W01 Italic' },
  { value: 'Didot', label: 'Didot' },
  { value: 'Della Respira, cursive', label: 'Della Respira' },
  //   { value: '"Didact Gothic", sans-serif', label: 'Didact Gothic' },
  { value: 'Georgia, serif', label: 'Georgia' },
  // { value: 'Helvetica nueue, sans-serif', label: 'Helvetica' },
  { value: 'Impact, sans-serif', label: 'Impact' },
  // { value: 'Inclusive Sans, sans-serif', label: 'Inclusive Sans' },
  { value: 'Inter, sans-serif', label: 'Inter' },
  { value: 'IvyMode', label: 'IvyMode' },
  { value: 'Lato, sans-serif', label: 'Lato' },
  { value: 'Lucida Console, monospace', label: 'Lucida Console' },
  { value: 'Lucida Sans Unicode, sans-serif', label: 'Lucida Sans Unicode' },
  { value: 'Montserrat, sans-serif', label: 'Montserrat' },
  // { value: 'Noto Sans, sans-serif', label: 'Noto Sans' },
  { value: 'Playfair, serif', label: 'Playfair' },
  { value: 'Open Sans, sans-serif', label: 'Open Sans' },
  // { value: 'Oswald, sans-serif', label: 'Oswald' },
  { value: 'Palatino Linotype, serif', label: 'Palatino Linotype' },
  { value: 'Roboto, sans-serif', label: 'Roboto' },
  { value: 'Tahoma, sans-serif', label: 'Tahoma' },
  { value: 'Times New Roman, serif', label: 'Times New Roman' },
  { value: 'Verdana, sans-serif', label: 'Verdana' },
  // { value: 'JosefinSans, sans-serif', label: 'JosefinSans' },
  { value: 'Preahvihear, sans-serif', label: 'Preahvihear' },
  { value: 'DM Sans, sans-serif', label: 'DM Sans' },
  { value: 'DM Mono', label: 'DM Mono' },
  { value: 'Pompiere', label: 'Pompiere' },
  { value: 'Poppins', label: 'Poppins' },
  { value: 'Ecriture', label: 'Ecriture' },
  { value: 'Old Standard TT', label: 'Old Standard TT' },
  { value: 'Pacifico', label: 'Pacifico' },
  { value: 'Bebas Neue', label: 'Bebas Neue' },
  { value: 'Anton SC', label: 'Anton SC' },
  { value: 'Nunito Sans', label: 'Nunito Sans' },
  { value: 'Segoe UI, sans-serif', label: 'Segoe UI' },
  { value: 'Calibri, sans-serif', label: 'Calibri' },
  { value: 'Cambria, serif', label: 'Cambria' },
  { value: 'Candara, sans-serif', label: 'Candara' },
  { value: 'Consolas, monospace', label: 'Consolas' },
  { value: 'Franklin Gothic, sans-serif', label: 'Franklin Gothic' },
  { value: 'Garamond, serif', label: 'Garamond' },
  { value: 'Century Gothic, sans-serif', label: 'Century Gothic' },
  { value: 'Trebuchet MS, sans-serif', label: 'Trebuchet MS' },
  { value: 'Book Antiqua, serif', label: 'Book Antiqua' },
  { value: 'Arial Narrow, sans-serif', label: 'Arial Narrow' },
  { value: 'MS Sans Serif, sans-serif', label: 'MS Sans Serif' },
  // { value: 'Futura, sans-serif', label: 'Futura' },
  { value: 'Baskerville, serif', label: 'Baskerville' },
  { value: 'Rockwell, serif', label: 'Rockwell' },
  { value: 'Perpetua, serif', label: 'Perpetua' },
  // { value: 'Gill Sans, sans-serif', label: 'Gill Sans' },
  { value: 'Copperplate, fantasy', label: 'Copperplate' },
  // { value: 'Optima, sans-serif', label: 'Optima' },
  // { value: 'Geneva, sans-serif', label: 'Geneva' },
  // { value: 'Helvetica Neue, sans-serif', label: 'Helvetica Neue' },
  // { value: 'Lucida Grande, sans-serif', label: 'Lucida Grande' },
  // { value: 'Monaco, monospace', label: 'Monaco' },
  { value: 'Palatino, serif', label: 'Palatino' },
  // { value: 'Cochin, serif', label: 'Cochin' },
  { value: 'PPAcma', label: 'PPAcma' },
  { value: 'HighriseDemo', label: 'HighriseDemo' },
  { value: 'BODAR', label: 'BODAR' },
  { value: 'Playfair Display SC', label: 'Playfair Display SC' },
  { value: 'Mulish', label: 'Mulish' },
  { value: 'Libre Baskerville', label: 'Libre Baskerville' },
  { value: 'Teko', label: 'Teko' },
  // { value: 'Avenir LT Pro 45 Book', label: 'Avenir LT Pro 45 Book' },
  { value: 'Merriweather, serif', label: 'Merriweather' },
  { value: 'Source Serif Pro, serif', label: 'Source Serif Pro' },
  // { value: 'Crimson Text, serif', label: 'Crimson Text' },
  { value: 'Spectral, serif', label: 'Spectral' },
  { value: 'Cormorant, serif', label: 'Cormorant' },
  // { value: 'Raleway, sans-serif', label: 'Raleway' },
  // { value: 'Quicksand, sans-serif', label: 'Quicksand' },
  { value: 'Abril Fatface, display', label: 'Abril Fatface' },
  // { value: 'Bodoni Moda, serif', label: 'Bodoni Moda' },
  // { value: 'Tenor Sans, sans-serif', label: 'Tenor Sans' },
  { value: 'Syne, sans-serif', label: 'Syne' },
  { value: 'Space Grotesk, sans-serif', label: 'Space Grotesk' },
  { value: 'Plus Jakarta Sans, sans-serif', label: 'Plus Jakarta Sans' },
  { value: 'Urbanist, sans-serif', label: 'Urbanist' },
  { value: 'Darker Grotesque, sans-serif', label: 'Darker Grotesque' },
  { value: 'Gloock, serif', label: 'Gloock' },
  { value: 'Unna, serif', label: 'Unna' },
  { value: 'Fraunces, serif', label: 'Fraunces' },
  { value: 'Instrument Serif, serif', label: 'Instrument Serif' },
  { value: 'Young Serif, serif', label: 'Young Serif' },
  { value: 'Marcellus, serif', label: 'Marcellus' },
  { value: 'Italiana, serif', label: 'Italiana' },
  { value: 'Antic Didone, serif', label: 'Antic Didone' },
  { value: 'GFS Didot, serif', label: 'GFS Didot' },
  { value: 'Cormorant Unicase, serif', label: 'Cormorant Unicase' },
  { value: 'Pinyon Script, cursive', label: 'Pinyon Script' },
  { value: 'Alex Brush, cursive', label: 'Alex Brush' },
  { value: 'Tangerine, cursive', label: 'Tangerine' },
  { value: 'Great Vibes, cursive', label: 'Great Vibes' },
  { value: 'Mrs Saint Delafield, cursive', label: 'Mrs Saint Delafield' },
  { value: 'Commissioner, sans-serif', label: 'Commissioner' },
  { value: 'Familjen Grotesk, sans-serif', label: 'Familjen Grotesk' },
  { value: 'Newsreader, serif', label: 'Newsreader' },
  // { value: 'Bricolage Grotesque, sans-serif', label: 'Bricolage Grotesque' },
  { value: 'Hedvig Letters Serif, serif', label: 'Hedvig Letters Serif' },
  { value: 'Marck Script', label: 'Marck Script' },
  // { value: 'Merriweather', label: 'Merriweather' },
  // { value: 'Della Respira', label: 'Della Respira' },
  { value: 'Didact Gothic', label: 'Didact Gothic' },
  { value: 'GTSuperDisplay', label: 'GT Super Display' },
  { value: 'AcuminProWide', label: 'Acumin Pro Wide' },
  { value: 'Dico Typewriter', label: 'Dico Typewriter' },
  { value: 'Gliker', label: 'Gliker' },
  { value: 'Gliker_Semibold', label: 'Gliker Semibold' },
  { value: 'Biscuitos', label: 'Biscuitos' },
  { value: 'Averta', label: 'Averta' },
  { value: 'Nunito', label: 'Nunito' },
];