import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import { ColorSchemeScript, MantineProvider, createTheme, Tooltip } from "@mantine/core";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ModalsProvider } from '@mantine/modals';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  components: {
    Tooltip: {
      defaultProps: {
        radius: "md",
      },
      styles: {
        tooltip: {
          backgroundColor: "var(--popover)",
          color: "var(--popover-foreground)",
          fontWeight: 400,
          boxShadow: "0px 2px 4px rgba(0, 0, 0, 0.1)",
        },
        arrow: {
          backgroundColor: "var(--popover)",
        },
      },
    },
    Select: {
      styles: {
        input: {
          backgroundColor: "var(--input)",
          borderColor: "var(--border)",
          color: "var(--title)",
          "&:focus": {
            borderColor: "var(--primary)",
          },
          "&::placeholder": {
            color: "var(--placeholder)",
          },
        },
        select: {
          color: "var(--title)",
        },
        dropdown: {
          backgroundColor: "var(--popover)",
          borderColor: "var(--border)",
          boxShadow: "0px 4px 16px 0px rgba(0, 0, 0, 0.1)",
          color: "var(--title)",
        },
        option: {
          color: "var(--title)",
          "&[data-combobox-selected]": {
            backgroundColor: "var(--primary) !important",
            color: "var(--title) !important",
          },
          "&:hover": {
            backgroundColor: "var(--secondary) !important",
          },
          "&[data-combobox-selected]:hover": {
            backgroundColor: "var(--primary) !important",
          },
        },
      },
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${inter.className} antialiased`}
      >
             <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >  <MantineProvider defaultColorScheme={"light"} forceColorScheme="light"theme={theme}>
                <ModalsProvider>
{children}</ModalsProvider>
</MantineProvider>
          </ThemeProvider>
       
      </body>
    </html>
  );
}
