/**
 * Footer section template JSON content
 */

import { TemplateNodeTree } from './hero-templates';

export const footerTemplate1: TemplateNodeTree = {
  rootNodeId: 'section',
  nodes: {
    section: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { background: '#0f172a', padding: '60px 20px', minHeight: 'auto', maxWidth: '1200px', flexDirection: 'column', alignItems: 'center', gap: 40 },
      displayName: 'Section',
      custom: { displayName: 'Footer', componentType: 'footer', isSection: true },
      nodes: ['columns', 'bottom'],
      linkedNodes: {},
    },
    columns: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'row', justifyContent: 'space-between', gap: 60, width: '100%' },
      displayName: 'Container',
      custom: { displayName: 'Footer Columns', isSection: false },
      parent: 'section',
      nodes: ['col1', 'col2', 'col3', 'col4'],
      linkedNodes: {},
    },
    col1: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'column', gap: 16 },
      displayName: 'Container',
      custom: { displayName: 'Column', isSection: false },
      parent: 'columns',
      nodes: ['logo', 'desc'],
      linkedNodes: {},
    },
    logo: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Company', fontSize: 20, fontWeight: 700, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Logo', isSection: false }, parent: 'col1', nodes: [], linkedNodes: {} },
    desc: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Building the future of web design.', fontSize: 14, color: '#94a3b8', lineHeight: 1.6 }, displayName: 'Text', custom: { displayName: 'Description', isSection: false }, parent: 'col1', nodes: [], linkedNodes: {} },
    col2: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'column', gap: 12 },
      displayName: 'Container',
      custom: { displayName: 'Column', isSection: false },
      parent: 'columns',
      nodes: ['h2', 'l1', 'l2', 'l3'],
      linkedNodes: {},
    },
    h2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Product', fontSize: 14, fontWeight: 600, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Heading', isSection: false }, parent: 'col2', nodes: [], linkedNodes: {} },
    l1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Features', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'col2', nodes: [], linkedNodes: {} },
    l2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Pricing', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'col2', nodes: [], linkedNodes: {} },
    l3: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Integrations', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'col2', nodes: [], linkedNodes: {} },
    col3: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'column', gap: 12 },
      displayName: 'Container',
      custom: { displayName: 'Column', isSection: false },
      parent: 'columns',
      nodes: ['h3', 'l4', 'l5', 'l6'],
      linkedNodes: {},
    },
    h3: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Company', fontSize: 14, fontWeight: 600, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Heading', isSection: false }, parent: 'col3', nodes: [], linkedNodes: {} },
    l4: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'About', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'col3', nodes: [], linkedNodes: {} },
    l5: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Careers', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'col3', nodes: [], linkedNodes: {} },
    l6: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Blog', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'col3', nodes: [], linkedNodes: {} },
    col4: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'column', gap: 12 },
      displayName: 'Container',
      custom: { displayName: 'Column', isSection: false },
      parent: 'columns',
      nodes: ['h4', 'l7', 'l8'],
      linkedNodes: {},
    },
    h4: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Legal', fontSize: 14, fontWeight: 600, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Heading', isSection: false }, parent: 'col4', nodes: [], linkedNodes: {} },
    l7: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Privacy', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'col4', nodes: [], linkedNodes: {} },
    l8: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Terms', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'col4', nodes: [], linkedNodes: {} },
    bottom: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: '© 2024 Company. All rights reserved.', fontSize: 14, color: '#64748b', textAlign: 'center' }, displayName: 'Text', custom: { displayName: 'Copyright', isSection: false }, parent: 'section', nodes: [], linkedNodes: {} },
  },
};

export const footerTemplate2: TemplateNodeTree = {
  rootNodeId: 'section',
  nodes: {
    section: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { background: '#1e293b', padding: '40px 20px', minHeight: 'auto', maxWidth: '1200px', flexDirection: 'column', alignItems: 'center', gap: 20 },
      displayName: 'Section',
      custom: { displayName: 'Footer', componentType: 'footer', isSection: true },
      nodes: ['logo', 'links', 'copy'],
      linkedNodes: {},
    },
    logo: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'BRAND', fontSize: 24, fontWeight: 700, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Logo', isSection: false }, parent: 'section', nodes: [], linkedNodes: {} },
    links: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'row', gap: 32 },
      displayName: 'Container',
      custom: { displayName: 'Links', isSection: false },
      parent: 'section',
      nodes: ['link1', 'link2', 'link3', 'link4'],
      linkedNodes: {},
    },
    link1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Home', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'links', nodes: [], linkedNodes: {} },
    link2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'About', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'links', nodes: [], linkedNodes: {} },
    link3: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Services', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'links', nodes: [], linkedNodes: {} },
    link4: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Contact', fontSize: 14, color: '#94a3b8' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'links', nodes: [], linkedNodes: {} },
    copy: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: '© 2024 All rights reserved.', fontSize: 12, color: '#64748b' }, displayName: 'Text', custom: { displayName: 'Copyright', isSection: false }, parent: 'section', nodes: [], linkedNodes: {} },
  },
};

export const footerTemplate3: TemplateNodeTree = {
  rootNodeId: 'section',
  nodes: {
    section: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { background: '#111827', padding: '60px 20px', minHeight: 'auto', maxWidth: '1200px', flexDirection: 'column', alignItems: 'center', gap: 32 },
      displayName: 'Section',
      custom: { displayName: 'Footer', componentType: 'footer', isSection: true },
      nodes: ['newsletter', 'divider', 'bottom'],
      linkedNodes: {},
    },
    newsletter: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'column', alignItems: 'center', gap: 16 },
      displayName: 'Container',
      custom: { displayName: 'Newsletter', isSection: false },
      parent: 'section',
      nodes: ['nlTitle', 'nlDesc', 'nlCta'],
      linkedNodes: {},
    },
    nlTitle: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Subscribe to our newsletter', fontSize: 24, fontWeight: 600, color: '#ffffff', textAlign: 'center' }, displayName: 'Text', custom: { displayName: 'Title', isSection: false }, parent: 'newsletter', nodes: [], linkedNodes: {} },
    nlDesc: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Get the latest updates and news directly in your inbox.', fontSize: 14, color: '#9ca3af', textAlign: 'center' }, displayName: 'Text', custom: { displayName: 'Description', isSection: false }, parent: 'newsletter', nodes: [], linkedNodes: {} },
    nlCta: { type: { resolvedName: 'Button' }, isCanvas: false, props: { text: 'Subscribe', fontSize: 14, fontWeight: 600, color: '#ffffff', background: '#6366f1', padding: '12px 28px', borderRadius: 8 }, displayName: 'Button', custom: { displayName: 'Subscribe Button', isSection: false }, parent: 'newsletter', nodes: [], linkedNodes: {} },
    divider: { type: { resolvedName: 'Container' }, isCanvas: false, props: { background: '#374151', width: '100%', height: '1px', padding: 0 }, displayName: 'Container', custom: { displayName: 'Divider', isSection: false }, parent: 'section', nodes: [], linkedNodes: {} },
    bottom: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'row', justifyContent: 'space-between', width: '100%' },
      displayName: 'Container',
      custom: { displayName: 'Bottom Row', isSection: false },
      parent: 'section',
      nodes: ['copy', 'social'],
      linkedNodes: {},
    },
    copy: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: '© 2024 Company Inc.', fontSize: 14, color: '#6b7280' }, displayName: 'Text', custom: { displayName: 'Copyright', isSection: false }, parent: 'bottom', nodes: [], linkedNodes: {} },
    social: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Twitter · LinkedIn · GitHub', fontSize: 14, color: '#6b7280' }, displayName: 'Text', custom: { displayName: 'Social Links', isSection: false }, parent: 'bottom', nodes: [], linkedNodes: {} },
  },
};

export const footerTemplate4: TemplateNodeTree = {
  rootNodeId: 'section',
  nodes: {
    section: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { background: '#18181b', padding: '48px 20px', minHeight: 'auto', maxWidth: '1200px', flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 40 },
      displayName: 'Section',
      custom: { displayName: 'Footer', componentType: 'footer', isSection: true },
      nodes: ['brand', 'links1', 'links2', 'contact'],
      linkedNodes: {},
    },
    brand: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'column', gap: 12, width: '30%' },
      displayName: 'Container',
      custom: { displayName: 'Brand', isSection: false },
      parent: 'section',
      nodes: ['logo', 'tagline'],
      linkedNodes: {},
    },
    logo: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: '🚀 StartUp', fontSize: 22, fontWeight: 700, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Logo', isSection: false }, parent: 'brand', nodes: [], linkedNodes: {} },
    tagline: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Empowering creators worldwide.', fontSize: 14, color: '#a1a1aa', lineHeight: 1.5 }, displayName: 'Text', custom: { displayName: 'Tagline', isSection: false }, parent: 'brand', nodes: [], linkedNodes: {} },
    links1: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'column', gap: 10 },
      displayName: 'Container',
      custom: { displayName: 'Links', isSection: false },
      parent: 'section',
      nodes: ['lh1', 'la1', 'la2'],
      linkedNodes: {},
    },
    lh1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Resources', fontSize: 14, fontWeight: 600, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Heading', isSection: false }, parent: 'links1', nodes: [], linkedNodes: {} },
    la1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Documentation', fontSize: 13, color: '#a1a1aa' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'links1', nodes: [], linkedNodes: {} },
    la2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Help Center', fontSize: 13, color: '#a1a1aa' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'links1', nodes: [], linkedNodes: {} },
    links2: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'column', gap: 10 },
      displayName: 'Container',
      custom: { displayName: 'Links', isSection: false },
      parent: 'section',
      nodes: ['lh2', 'lb1', 'lb2'],
      linkedNodes: {},
    },
    lh2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Company', fontSize: 14, fontWeight: 600, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Heading', isSection: false }, parent: 'links2', nodes: [], linkedNodes: {} },
    lb1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'About Us', fontSize: 13, color: '#a1a1aa' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'links2', nodes: [], linkedNodes: {} },
    lb2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Careers', fontSize: 13, color: '#a1a1aa' }, displayName: 'Text', custom: { displayName: 'Link', isSection: false }, parent: 'links2', nodes: [], linkedNodes: {} },
    contact: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { background: 'transparent', padding: 0, flexDirection: 'column', gap: 10 },
      displayName: 'Container',
      custom: { displayName: 'Contact', isSection: false },
      parent: 'section',
      nodes: ['ch', 'email'],
      linkedNodes: {},
    },
    ch: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Contact', fontSize: 14, fontWeight: 600, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Heading', isSection: false }, parent: 'contact', nodes: [], linkedNodes: {} },
    email: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'hello@startup.com', fontSize: 13, color: '#a1a1aa' }, displayName: 'Text', custom: { displayName: 'Email', isSection: false }, parent: 'contact', nodes: [], linkedNodes: {} },
  },
};

export const FOOTER_TEMPLATES: Record<string, TemplateNodeTree> = {
  'footer-1': footerTemplate1,
  'footer-2': footerTemplate2,
  'footer-3': footerTemplate3,
  'footer-4': footerTemplate4,
};
