/**
 * Team, Gallery, Services, and Features section templates
 */

import { TemplateNodeTree } from './hero-templates';

// ============ TEAM TEMPLATES ============

export const teamTemplate1: TemplateNodeTree = {
  rootNodeId: 'section',
  nodes: {
    section: { type: { resolvedName: 'Section' }, isCanvas: true, props: { background: '#f8fafc', padding: '80px 20px', maxWidth: '1200px', flexDirection: 'column', alignItems: 'center', gap: 40 }, displayName: 'Section', custom: { displayName: 'Team Section', componentType: 'team', isSection: true }, nodes: ['title', 'grid'], linkedNodes: {} },
    title: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Meet Our Team', fontSize: 32, fontWeight: 700, color: '#1e293b', textAlign: 'center', tagName: 'h2' }, displayName: 'Text', custom: { displayName: 'Title', isSection: false }, parent: 'section', nodes: [], linkedNodes: {} },
    grid: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'transparent', padding: 0, flexDirection: 'row', gap: 32, justifyContent: 'center' }, displayName: 'Container', custom: { displayName: 'Grid', isSection: false }, parent: 'section', nodes: ['m1', 'm2', 'm3'], linkedNodes: {} },
    m1: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: '#ffffff', padding: 24, flexDirection: 'column', alignItems: 'center', gap: 12, width: '250px', borderRadius: 12 }, displayName: 'Container', custom: { displayName: 'Member', isSection: false }, parent: 'grid', nodes: ['i1', 'n1', 'r1'], linkedNodes: {} },
    i1: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&h=200&q=80', width: '120px', height: '120px', borderRadius: 60 }, displayName: 'Image', custom: { displayName: 'Photo', isSection: false }, parent: 'm1', nodes: [], linkedNodes: {} },
    n1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'John Doe', fontSize: 18, fontWeight: 600, color: '#1e293b' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'm1', nodes: [], linkedNodes: {} },
    r1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'CEO', fontSize: 14, color: '#64748b' }, displayName: 'Text', custom: { displayName: 'Role', isSection: false }, parent: 'm1', nodes: [], linkedNodes: {} },
    m2: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: '#ffffff', padding: 24, flexDirection: 'column', alignItems: 'center', gap: 12, width: '250px', borderRadius: 12 }, displayName: 'Container', custom: { displayName: 'Member', isSection: false }, parent: 'grid', nodes: ['i2', 'n2', 'r2'], linkedNodes: {} },
    i2: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&h=200&q=80', width: '120px', height: '120px', borderRadius: 60 }, displayName: 'Image', custom: { displayName: 'Photo', isSection: false }, parent: 'm2', nodes: [], linkedNodes: {} },
    n2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Jane Smith', fontSize: 18, fontWeight: 600, color: '#1e293b' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'm2', nodes: [], linkedNodes: {} },
    r2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'CTO', fontSize: 14, color: '#64748b' }, displayName: 'Text', custom: { displayName: 'Role', isSection: false }, parent: 'm2', nodes: [], linkedNodes: {} },
    m3: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: '#ffffff', padding: 24, flexDirection: 'column', alignItems: 'center', gap: 12, width: '250px', borderRadius: 12 }, displayName: 'Container', custom: { displayName: 'Member', isSection: false }, parent: 'grid', nodes: ['i3', 'n3', 'r3'], linkedNodes: {} },
    i3: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&h=200&q=80', width: '120px', height: '120px', borderRadius: 60 }, displayName: 'Image', custom: { displayName: 'Photo', isSection: false }, parent: 'm3', nodes: [], linkedNodes: {} },
    n3: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Mike Johnson', fontSize: 18, fontWeight: 600, color: '#1e293b' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'm3', nodes: [], linkedNodes: {} },
    r3: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Designer', fontSize: 14, color: '#64748b' }, displayName: 'Text', custom: { displayName: 'Role', isSection: false }, parent: 'm3', nodes: [], linkedNodes: {} },
  },
};

export const teamTemplate2: TemplateNodeTree = {
  rootNodeId: 'section',
  nodes: {
    section: { type: { resolvedName: 'Section' }, isCanvas: true, props: { background: '#ffffff', padding: '80px 20px', maxWidth: '1200px', flexDirection: 'column', alignItems: 'center', gap: 40 }, displayName: 'Section', custom: { displayName: 'Team Section', componentType: 'team', isSection: true }, nodes: ['header', 'grid'], linkedNodes: {} },
    header: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'transparent', padding: 0, flexDirection: 'column', alignItems: 'center', gap: 8 }, displayName: 'Container', custom: { displayName: 'Header', isSection: false }, parent: 'section', nodes: ['title', 'sub'], linkedNodes: {} },
    title: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Our Leadership', fontSize: 36, fontWeight: 700, color: '#0f172a', textAlign: 'center', tagName: 'h2' }, displayName: 'Text', custom: { displayName: 'Title', isSection: false }, parent: 'header', nodes: [], linkedNodes: {} },
    sub: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'The people behind our success', fontSize: 16, color: '#64748b', textAlign: 'center' }, displayName: 'Text', custom: { displayName: 'Subtitle', isSection: false }, parent: 'header', nodes: [], linkedNodes: {} },
    grid: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'transparent', padding: 0, flexDirection: 'row', gap: 24, justifyContent: 'center' }, displayName: 'Container', custom: { displayName: 'Grid', isSection: false }, parent: 'section', nodes: ['c1', 'c2'], linkedNodes: {} },
    c1: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: '#f1f5f9', padding: 32, flexDirection: 'column', alignItems: 'center', gap: 16, width: '300px', borderRadius: 16 }, displayName: 'Container', custom: { displayName: 'Card', isSection: false }, parent: 'grid', nodes: ['img1', 'name1', 'role1', 'bio1'], linkedNodes: {} },
    img1: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&h=200&q=80', width: '100px', height: '100px', borderRadius: 50 }, displayName: 'Image', custom: { displayName: 'Photo', isSection: false }, parent: 'c1', nodes: [], linkedNodes: {} },
    name1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'David Chen', fontSize: 20, fontWeight: 600, color: '#0f172a' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'c1', nodes: [], linkedNodes: {} },
    role1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Founder & CEO', fontSize: 14, fontWeight: 500, color: '#6366f1' }, displayName: 'Text', custom: { displayName: 'Role', isSection: false }, parent: 'c1', nodes: [], linkedNodes: {} },
    bio1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: '15+ years of experience in tech leadership.', fontSize: 14, color: '#64748b', textAlign: 'center' }, displayName: 'Text', custom: { displayName: 'Bio', isSection: false }, parent: 'c1', nodes: [], linkedNodes: {} },
    c2: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: '#f1f5f9', padding: 32, flexDirection: 'column', alignItems: 'center', gap: 16, width: '300px', borderRadius: 16 }, displayName: 'Container', custom: { displayName: 'Card', isSection: false }, parent: 'grid', nodes: ['img2', 'name2', 'role2', 'bio2'], linkedNodes: {} },
    img2: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&h=200&q=80', width: '100px', height: '100px', borderRadius: 50 }, displayName: 'Image', custom: { displayName: 'Photo', isSection: false }, parent: 'c2', nodes: [], linkedNodes: {} },
    name2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Sarah Miller', fontSize: 20, fontWeight: 600, color: '#0f172a' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'c2', nodes: [], linkedNodes: {} },
    role2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Head of Product', fontSize: 14, fontWeight: 500, color: '#6366f1' }, displayName: 'Text', custom: { displayName: 'Role', isSection: false }, parent: 'c2', nodes: [], linkedNodes: {} },
    bio2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Former product lead at a Fortune 500 company.', fontSize: 14, color: '#64748b', textAlign: 'center' }, displayName: 'Text', custom: { displayName: 'Bio', isSection: false }, parent: 'c2', nodes: [], linkedNodes: {} },
  },
};

export const teamTemplate3: TemplateNodeTree = {
  rootNodeId: 'section',
  nodes: {
    section: { type: { resolvedName: 'Section' }, isCanvas: true, props: { background: '#ffffff', padding: '60px 20px', maxWidth: '1200px', flexDirection: 'column', alignItems: 'center', gap: 32 }, displayName: 'Section', custom: { displayName: 'Team Section', componentType: 'team', isSection: true }, nodes: ['title', 'row'], linkedNodes: {} },
    title: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'The Team', fontSize: 28, fontWeight: 700, color: '#1e293b', tagName: 'h2' }, displayName: 'Text', custom: { displayName: 'Title', isSection: false }, parent: 'section', nodes: [], linkedNodes: {} },
    row: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'transparent', padding: 0, flexDirection: 'row', gap: 40, justifyContent: 'center' }, displayName: 'Container', custom: { displayName: 'Row', isSection: false }, parent: 'section', nodes: ['p1', 'p2', 'p3', 'p4'], linkedNodes: {} },
    p1: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'transparent', padding: 0, flexDirection: 'column', alignItems: 'center', gap: 8 }, displayName: 'Container', custom: { displayName: 'Person', isSection: false }, parent: 'row', nodes: ['a1', 'nm1'], linkedNodes: {} },
    a1: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&h=100&q=80', width: '64px', height: '64px', borderRadius: 32 }, displayName: 'Image', custom: { displayName: 'Avatar', isSection: false }, parent: 'p1', nodes: [], linkedNodes: {} },
    nm1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Alex', fontSize: 14, fontWeight: 500, color: '#374151' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'p1', nodes: [], linkedNodes: {} },
    p2: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'transparent', padding: 0, flexDirection: 'column', alignItems: 'center', gap: 8 }, displayName: 'Container', custom: { displayName: 'Person', isSection: false }, parent: 'row', nodes: ['a2', 'nm2'], linkedNodes: {} },
    a2: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&h=100&q=80', width: '64px', height: '64px', borderRadius: 32 }, displayName: 'Image', custom: { displayName: 'Avatar', isSection: false }, parent: 'p2', nodes: [], linkedNodes: {} },
    nm2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Emma', fontSize: 14, fontWeight: 500, color: '#374151' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'p2', nodes: [], linkedNodes: {} },
    p3: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'transparent', padding: 0, flexDirection: 'column', alignItems: 'center', gap: 8 }, displayName: 'Container', custom: { displayName: 'Person', isSection: false }, parent: 'row', nodes: ['a3', 'nm3'], linkedNodes: {} },
    a3: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=100&h=100&q=80', width: '64px', height: '64px', borderRadius: 32 }, displayName: 'Image', custom: { displayName: 'Avatar', isSection: false }, parent: 'p3', nodes: [], linkedNodes: {} },
    nm3: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Chris', fontSize: 14, fontWeight: 500, color: '#374151' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'p3', nodes: [], linkedNodes: {} },
    p4: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'transparent', padding: 0, flexDirection: 'column', alignItems: 'center', gap: 8 }, displayName: 'Container', custom: { displayName: 'Person', isSection: false }, parent: 'row', nodes: ['a4', 'nm4'], linkedNodes: {} },
    a4: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=100&h=100&q=80', width: '64px', height: '64px', borderRadius: 32 }, displayName: 'Image', custom: { displayName: 'Avatar', isSection: false }, parent: 'p4', nodes: [], linkedNodes: {} },
    nm4: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Ryan', fontSize: 14, fontWeight: 500, color: '#374151' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'p4', nodes: [], linkedNodes: {} },
  },
};

export const teamTemplate4: TemplateNodeTree = {
  rootNodeId: 'section',
  nodes: {
    section: { type: { resolvedName: 'Section' }, isCanvas: true, props: { background: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)', padding: '80px 20px', maxWidth: '1200px', flexDirection: 'column', alignItems: 'center', gap: 40 }, displayName: 'Section', custom: { displayName: 'Team Section', componentType: 'team', isSection: true }, nodes: ['title', 'grid'], linkedNodes: {} },
    title: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Creative Minds', fontSize: 36, fontWeight: 700, color: '#ffffff', textAlign: 'center', tagName: 'h2' }, displayName: 'Text', custom: { displayName: 'Title', isSection: false }, parent: 'section', nodes: [], linkedNodes: {} },
    grid: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'transparent', padding: 0, flexDirection: 'row', gap: 24, justifyContent: 'center' }, displayName: 'Container', custom: { displayName: 'Grid', isSection: false }, parent: 'section', nodes: ['card1', 'card2', 'card3'], linkedNodes: {} },
    card1: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'rgba(255,255,255,0.1)', padding: 24, flexDirection: 'column', alignItems: 'center', gap: 12, width: '220px', borderRadius: 16 }, displayName: 'Container', custom: { displayName: 'Card', isSection: false }, parent: 'grid', nodes: ['img1', 'name1', 'role1'], linkedNodes: {} },
    img1: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&h=150&q=80', width: '100px', height: '100px', borderRadius: 50 }, displayName: 'Image', custom: { displayName: 'Photo', isSection: false }, parent: 'card1', nodes: [], linkedNodes: {} },
    name1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Luna Ray', fontSize: 18, fontWeight: 600, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'card1', nodes: [], linkedNodes: {} },
    role1: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Art Director', fontSize: 13, color: '#a5b4fc' }, displayName: 'Text', custom: { displayName: 'Role', isSection: false }, parent: 'card1', nodes: [], linkedNodes: {} },
    card2: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'rgba(255,255,255,0.1)', padding: 24, flexDirection: 'column', alignItems: 'center', gap: 12, width: '220px', borderRadius: 16 }, displayName: 'Container', custom: { displayName: 'Card', isSection: false }, parent: 'grid', nodes: ['img2', 'name2', 'role2'], linkedNodes: {} },
    img2: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&h=150&q=80', width: '100px', height: '100px', borderRadius: 50 }, displayName: 'Image', custom: { displayName: 'Photo', isSection: false }, parent: 'card2', nodes: [], linkedNodes: {} },
    name2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Max Storm', fontSize: 18, fontWeight: 600, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'card2', nodes: [], linkedNodes: {} },
    role2: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Lead Dev', fontSize: 13, color: '#a5b4fc' }, displayName: 'Text', custom: { displayName: 'Role', isSection: false }, parent: 'card2', nodes: [], linkedNodes: {} },
    card3: { type: { resolvedName: 'Container' }, isCanvas: true, props: { background: 'rgba(255,255,255,0.1)', padding: 24, flexDirection: 'column', alignItems: 'center', gap: 12, width: '220px', borderRadius: 16 }, displayName: 'Container', custom: { displayName: 'Card', isSection: false }, parent: 'grid', nodes: ['img3', 'name3', 'role3'], linkedNodes: {} },
    img3: { type: { resolvedName: 'Image' }, isCanvas: false, props: { src: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&h=150&q=80', width: '100px', height: '100px', borderRadius: 50 }, displayName: 'Image', custom: { displayName: 'Photo', isSection: false }, parent: 'card3', nodes: [], linkedNodes: {} },
    name3: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'Ivy Green', fontSize: 18, fontWeight: 600, color: '#ffffff' }, displayName: 'Text', custom: { displayName: 'Name', isSection: false }, parent: 'card3', nodes: [], linkedNodes: {} },
    role3: { type: { resolvedName: 'Text' }, isCanvas: false, props: { text: 'UX Lead', fontSize: 13, color: '#a5b4fc' }, displayName: 'Text', custom: { displayName: 'Role', isSection: false }, parent: 'card3', nodes: [], linkedNodes: {} },
  },
};

export const TEAM_TEMPLATES: Record<string, TemplateNodeTree> = { 'team-1': teamTemplate1, 'team-2': teamTemplate2, 'team-3': teamTemplate3, 'team-4': teamTemplate4 };
