// Default template JSON for Craft.js
// This represents a full website with header, hero, content sections, and footer
// The JSON follows Craft.js node schema precisely
//
// IMPORTANT: See TEMPLATE_COMPONENT_IDENTIFICATION.md for rules on component identification

export const defaultTemplate = {
  ROOT: {
    type: { resolvedName: "Root" },
    isCanvas: true,
    props: {
      background: "#ffffff",
    },
    displayName: "Root",
    custom: {
      displayName: "Page",
      isSection: false,
    },
    hidden: false,
    nodes: ["header", "hero", "features", "cta", "footer"],
    linkedNodes: {},
  },
  header: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#1e293b",
      padding: "16px 20px",
      minHeight: "auto",
      maxWidth: "1200px",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 20,
    },
    displayName: "Section",
    custom: {
      displayName: "Header",
      componentType: "navbar",
      isSection: true,
    },
    parent: "ROOT",
    hidden: false,
    nodes: ["header-logo", "header-nav"],
    linkedNodes: {},
  },
  "header-logo": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Logo",
      fontSize: 24,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "left",
      tagName: "h1",
    },
    displayName: "Text",
    custom: {
      displayName: "Logo",
      isSection: false,
    },
    parent: "header",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "header-nav": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "transparent",
      padding: 0,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 24,
    },
    displayName: "Container",
    custom: {
      displayName: "Navigation",
      isSection: false,
    },
    parent: "header",
    hidden: false,
    nodes: ["nav-home", "nav-about", "nav-services", "nav-contact"],
    linkedNodes: {},
  },
  "nav-home": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Home",
      fontSize: 14,
      fontWeight: 500,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Nav Link",
      isSection: false,
    },
    parent: "header-nav",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "nav-about": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "About",
      fontSize: 14,
      fontWeight: 500,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Nav Link",
      isSection: false,
    },
    parent: "header-nav",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "nav-services": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Services",
      fontSize: 14,
      fontWeight: 500,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Nav Link",
      isSection: false,
    },
    parent: "header-nav",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "nav-contact": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Contact",
      fontSize: 14,
      fontWeight: 500,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Nav Link",
      isSection: false,
    },
    parent: "header-nav",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hero: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      padding: "100px 20px",
      minHeight: "500px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 24,
    },
    displayName: "Section",
    custom: {
      displayName: "Hero Section",
      componentType: "hero",
      isSection: true,
    },
    parent: "ROOT",
    hidden: false,
    nodes: ["hero-title", "hero-subtitle", "hero-cta"],
    linkedNodes: {},
  },
  "hero-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Build Beautiful Websites",
      fontSize: 48,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "center",
      tagName: "h1",
    },
    displayName: "Text",
    custom: {
      displayName: "Hero Title",
      isSection: false,
    },
    parent: "hero",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "hero-subtitle": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Create stunning, responsive websites with our intuitive drag-and-drop builder. No coding required.",
      fontSize: 20,
      fontWeight: 400,
      color: "rgba(255,255,255,0.9)",
      textAlign: "center",
      lineHeight: 1.6,
    },
    displayName: "Text",
    custom: {
      displayName: "Hero Subtitle",
      isSection: false,
    },
    parent: "hero",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "hero-cta": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "Get Started Free",
      fontSize: 18,
      fontWeight: 600,
      color: "#667eea",
      background: "#ffffff",
      padding: "16px 40px",
      borderRadius: 30,
    },
    displayName: "Button",
    custom: {
      displayName: "CTA Button",
      isSection: false,
    },
    parent: "hero",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  features: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#f8fafc",
      padding: "80px 20px",
      minHeight: "auto",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 48,
    },
    displayName: "Section",
    custom: {
      displayName: "Features Section",
      componentType: "features",
      isSection: true,
    },
    parent: "ROOT",
    hidden: false,
    nodes: ["features-title", "features-grid"],
    linkedNodes: {},
  },
  "features-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Why Choose Us",
      fontSize: 36,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: {
      displayName: "Section Title",
      isSection: false,
    },
    parent: "features",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "features-grid": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "transparent",
      padding: 0,
      flexDirection: "row",
      alignItems: "stretch",
      justifyContent: "center",
      gap: 32,
      width: "100%",
    },
    displayName: "Container",
    custom: {
      displayName: "Features Grid",
      isSection: false,
    },
    parent: "features",
    hidden: false,
    nodes: ["feature-1", "feature-2", "feature-3"],
    linkedNodes: {},
  },
  "feature-1": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 32,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: 16,
      width: "300px",
    },
    displayName: "Container",
    custom: {
      displayName: "Feature Card",
      isSection: false,
    },
    parent: "features-grid",
    hidden: false,
    nodes: ["feature-1-title", "feature-1-desc"],
    linkedNodes: {},
  },
  "feature-1-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Easy to Use",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h3",
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Title",
      isSection: false,
    },
    parent: "feature-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-1-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Intuitive drag-and-drop interface that anyone can master in minutes.",
      fontSize: 14,
      fontWeight: 400,
      color: "#64748b",
      textAlign: "center",
      lineHeight: 1.6,
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Description",
      isSection: false,
    },
    parent: "feature-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-2": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 32,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: 16,
      width: "300px",
    },
    displayName: "Container",
    custom: {
      displayName: "Feature Card",
      isSection: false,
    },
    parent: "features-grid",
    hidden: false,
    nodes: ["feature-2-title", "feature-2-desc"],
    linkedNodes: {},
  },
  "feature-2-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Fully Responsive",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h3",
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Title",
      isSection: false,
    },
    parent: "feature-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-2-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Your website looks perfect on desktop, tablet, and mobile devices.",
      fontSize: 14,
      fontWeight: 400,
      color: "#64748b",
      textAlign: "center",
      lineHeight: 1.6,
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Description",
      isSection: false,
    },
    parent: "feature-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-3": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 32,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: 16,
      width: "300px",
    },
    displayName: "Container",
    custom: {
      displayName: "Feature Card",
      isSection: false,
    },
    parent: "features-grid",
    hidden: false,
    nodes: ["feature-3-title", "feature-3-desc"],
    linkedNodes: {},
  },
  "feature-3-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Lightning Fast",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h3",
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Title",
      isSection: false,
    },
    parent: "feature-3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-3-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Optimized performance ensures your site loads instantly every time.",
      fontSize: 14,
      fontWeight: 400,
      color: "#64748b",
      textAlign: "center",
      lineHeight: 1.6,
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Description",
      isSection: false,
    },
    parent: "feature-3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  cta: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#1e293b",
      padding: "80px 20px",
      minHeight: "auto",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 24,
    },
    displayName: "Section",
    custom: {
      displayName: "CTA Section",
      componentType: "cta",
      isSection: true,
    },
    parent: "ROOT",
    hidden: false,
    nodes: ["cta-title", "cta-desc", "cta-button"],
    linkedNodes: {},
  },
  "cta-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Ready to Get Started?",
      fontSize: 36,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: {
      displayName: "CTA Title",
      isSection: false,
    },
    parent: "cta",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "cta-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Join thousands of happy customers building their dream websites today.",
      fontSize: 18,
      fontWeight: 400,
      color: "rgba(255,255,255,0.8)",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "CTA Description",
      isSection: false,
    },
    parent: "cta",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "cta-button": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "Start Building Now",
      fontSize: 18,
      fontWeight: 600,
      color: "#1e293b",
      background: "#22d3ee",
      padding: "16px 40px",
      borderRadius: 8,
    },
    displayName: "Button",
    custom: {
      displayName: "CTA Button",
      isSection: false,
    },
    parent: "cta",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  footer: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#0f172a",
      padding: "40px 20px",
      minHeight: "auto",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 16,
    },
    displayName: "Section",
    custom: {
      displayName: "Footer",
      componentType: "footer",
      isSection: true,
    },
    parent: "ROOT",
    hidden: false,
    nodes: ["footer-text", "footer-copyright"],
    linkedNodes: {},
  },
  "footer-text": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Logo",
      fontSize: 20,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Footer Logo",
      isSection: false,
    },
    parent: "footer",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "footer-copyright": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "© 2026 Your Brand. All rights reserved.",
      fontSize: 14,
      fontWeight: 400,
      color: "rgba(255,255,255,0.6)",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Copyright",
      isSection: false,
    },
    parent: "footer",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};

// Helper function to get the template as a serialized string
export const getSerializedTemplate = () => JSON.stringify(defaultTemplate);
