// Default template JSON for Craft.js
// This represents a full website with header, hero, content sections, and footer
// The JSON follows Craft.js node schema precisely
//
// IMPORTANT: See TEMPLATE_COMPONENT_IDENTIFICATION.md for rules on component identification

export const defaultTemplate = {
  ROOT: {
    type: { resolvedName: "Root" },
    isCanvas: true,
    props: {
      background: "#ffffff",
    },
    displayName: "Root",
    custom: {
      displayName: "Page",
      isSection: false,
    },
    hidden: false,
    nodes: [
      "header",
      "hero",
      "about",
      "banner",
      "team",
      "gallery",
      "services",
      "features",
      "socials",
      "newsletter",
      "testimonials",
      "casestudies",
      "whyjoinus",
      "privacypolicy",
      "pricing",
      "termsofservice",
      "resources",
      "contact",
      "faq",
      "blogs",
      "product",
      "footer"
    ],
    linkedNodes: {},
  },
  header: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#1e293b",
      padding: "16px 20px",
      minHeight: "auto",
      maxWidth: "1200px",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 20,
    },
    displayName: "Section",
    custom: {
      displayName: "Header",
      componentType: "navbar",
      isSection: true,
    },
    parent: "ROOT",
    hidden: false,
    nodes: ["header-logo", "header-nav"],
    linkedNodes: {},
  },
  "header-logo": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Logo",
      fontSize: 24,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "left",
      tagName: "h1",
    },
    displayName: "Text",
    custom: {
      displayName: "Logo",
      isSection: false,
    },
    parent: "header",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "header-nav": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "transparent",
      padding: 0,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 24,
    },
    displayName: "Container",
    custom: {
      displayName: "Navigation",
      isSection: false,
    },
    parent: "header",
    hidden: false,
    nodes: ["nav-home", "nav-about", "nav-services", "nav-contact"],
    linkedNodes: {},
  },
  "nav-home": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Home",
      fontSize: 14,
      fontWeight: 500,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Nav Link",
      isSection: false,
    },
    parent: "header-nav",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "nav-about": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "About",
      fontSize: 14,
      fontWeight: 500,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Nav Link",
      isSection: false,
    },
    parent: "header-nav",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "nav-services": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Services",
      fontSize: 14,
      fontWeight: 500,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Nav Link",
      isSection: false,
    },
    parent: "header-nav",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "nav-contact": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Contact",
      fontSize: 14,
      fontWeight: 500,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Nav Link",
      isSection: false,
    },
    parent: "header-nav",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hero: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      padding: "100px 20px",
      minHeight: "500px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 24,
    },
    displayName: "Section",
    custom: {
      displayName: "Hero Section",
      componentType: "hero",
      isSection: true,
    },
    parent: "ROOT",
    hidden: false,
    nodes: ["hero-title", "hero-subtitle", "hero-cta"],
    linkedNodes: {},
  },
  "hero-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Build Beautiful Websites",
      fontSize: 48,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "center",
      tagName: "h1",
    },
    displayName: "Text",
    custom: {
      displayName: "Hero Title",
      isSection: false,
    },
    parent: "hero",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "hero-subtitle": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Create stunning, responsive websites with our intuitive drag-and-drop builder. No coding required.",
      fontSize: 20,
      fontWeight: 400,
      color: "rgba(255,255,255,0.9)",
      textAlign: "center",
      lineHeight: 1.6,
    },
    displayName: "Text",
    custom: {
      displayName: "Hero Subtitle",
      isSection: false,
    },
    parent: "hero",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "hero-cta": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "Get Started Free",
      fontSize: 18,
      fontWeight: 600,
      color: "#667eea",
      background: "#ffffff",
      padding: "16px 40px",
      borderRadius: 30,
    },
    displayName: "Button",
    custom: {
      displayName: "CTA Button",
      isSection: false,
    },
    parent: "hero",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  about: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: "80px 20px",
      minHeight: "auto",
      maxWidth: "1200px",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 40,
    },
    displayName: "Section",
    custom: { displayName: "About Section", componentType: "about", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["about-image", "about-content"],
    linkedNodes: {},
  },
  "about-image": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80",
      alt: "About Us",
      width: "500px",
      height: "400px",
      borderRadius: 8,
    },
    displayName: "Image",
    custom: { displayName: "About Image", isSection: false },
    parent: "about",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "about-content": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "transparent",
      padding: 0,
      flexDirection: "column",
      alignItems: "flex-start",
      justifyContent: "center",
      gap: 16,
      width: "500px",
    },
    displayName: "Container",
    custom: { displayName: "About Content", isSection: false },
    parent: "about",
    hidden: false,
    nodes: ["about-title", "about-desc"],
    linkedNodes: {},
  },
  "about-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "About Our Company",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "left",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "About Title", isSection: false },
    parent: "about-content",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "about-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "We are dedicated to providing the best service. Our team works hard to ensure customer satisfaction and deliver high-quality products.",
      fontSize: 16,
      fontWeight: 400,
      color: "#475569",
      textAlign: "left",
      lineHeight: 1.6,
    },
    displayName: "Text",
    custom: { displayName: "About Description", isSection: false },
    parent: "about-content",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  banner: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      padding: "60px 20px",
      minHeight: "auto",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 20,
    },
    displayName: "Section",
    custom: { displayName: "Banner", componentType: "banner", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["banner-text", "banner-subtext"],
    linkedNodes: {},
  },
  "banner-text": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Special Offer: Get 50% Off Today!",
      fontSize: 28,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: { displayName: "Banner Text", isSection: false },
    parent: "banner",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "banner-subtext": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Limited time only. Don't miss out.",
      fontSize: 16,
      fontWeight: 400,
      color: "rgba(255,255,255,0.9)",
      textAlign: "center",
    },
    displayName: "Text",
    custom: { displayName: "Banner Subtext", isSection: false },
    parent: "banner",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  team: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#f8fafc",
      padding: "80px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 40,
    },
    displayName: "Section",
    custom: { displayName: "Team Section", componentType: "team", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["team-title", "team-grid"],
    linkedNodes: {},
  },
  "team-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Meet Our Team",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "Team Title", isSection: false },
    parent: "team",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "team-grid": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 32,
      background: "transparent",
      padding: 0,
    },
    displayName: "Container",
    custom: { displayName: "Team Grid", isSection: false },
    parent: "team",
    hidden: false,
    nodes: ["team-member-1", "team-member-2", "team-member-3"],
    linkedNodes: {},
  },
  "team-member-1": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 24,
      flexDirection: "column",
      alignItems: "center",
      gap: 16,
      width: "250px",
    },
    displayName: "Container",
    custom: { displayName: "Team Member", isSection: false },
    parent: "team-grid",
    hidden: false,
    nodes: ["tm-1-img", "tm-1-name", "tm-1-role"],
    linkedNodes: {},
  },
  "tm-1-img": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&h=200&q=80",
      width: "150px",
      height: "150px",
      borderRadius: 75,
      objectFit: "cover",
    },
    displayName: "Image",
    custom: { displayName: "Member Photo", isSection: false },
    parent: "team-member-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "tm-1-name": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "John Doe",
      fontSize: 18,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Member Name", isSection: false },
    parent: "team-member-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "tm-1-role": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "CEO",
      fontSize: 14,
      color: "#64748b",
    },
    displayName: "Text",
    custom: { displayName: "Member Role", isSection: false },
    parent: "team-member-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "team-member-2": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 24,
      flexDirection: "column",
      alignItems: "center",
      gap: 16,
      width: "250px",
    },
    displayName: "Container",
    custom: { displayName: "Team Member", isSection: false },
    parent: "team-grid",
    hidden: false,
    nodes: ["tm-2-img", "tm-2-name", "tm-2-role"],
    linkedNodes: {},
  },
  "tm-2-img": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&h=200&q=80",
      width: "150px",
      height: "150px",
      borderRadius: 75,
      objectFit: "cover",
    },
    displayName: "Image",
    custom: { displayName: "Member Photo", isSection: false },
    parent: "team-member-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "tm-2-name": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Jane Smith",
      fontSize: 18,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Member Name", isSection: false },
    parent: "team-member-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "tm-2-role": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "CTO",
      fontSize: 14,
      color: "#64748b",
    },
    displayName: "Text",
    custom: { displayName: "Member Role", isSection: false },
    parent: "team-member-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "team-member-3": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 24,
      flexDirection: "column",
      alignItems: "center",
      gap: 16,
      width: "250px",
    },
    displayName: "Container",
    custom: { displayName: "Team Member", isSection: false },
    parent: "team-grid",
    hidden: false,
    nodes: ["tm-3-img", "tm-3-name", "tm-3-role"],
    linkedNodes: {},
  },
  "tm-3-img": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&h=200&q=80",
      width: "150px",
      height: "150px",
      borderRadius: 75,
      objectFit: "cover",
    },
    displayName: "Image",
    custom: { displayName: "Member Photo", isSection: false },
    parent: "team-member-3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "tm-3-name": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Mike Johnson",
      fontSize: 18,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Member Name", isSection: false },
    parent: "team-member-3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "tm-3-role": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Lead Designer",
      fontSize: 14,
      color: "#64748b",
    },
    displayName: "Text",
    custom: { displayName: "Member Role", isSection: false },
    parent: "team-member-3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  gallery: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: "80px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 30,
    },
    displayName: "Section",
    custom: { displayName: "Gallery", componentType: "gallery", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["gallery-title", "gallery-grid"],
    linkedNodes: {},
  },
  "gallery-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Our Gallery",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "Gallery Title", isSection: false },
    parent: "gallery",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "gallery-grid": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "transparent",
      padding: 0,
      flexDirection: "row",
      justifyContent: "center",
      gap: 20,
    },
    displayName: "Container",
    custom: { displayName: "Gallery Grid", isSection: false },
    parent: "gallery",
    hidden: false,
    nodes: ["gal-img-1", "gal-img-2", "gal-img-3"],
    linkedNodes: {},
  },
  "gal-img-1": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=400&h=300&q=80",
      width: "300px",
      height: "200px",
      borderRadius: 8,
    },
    displayName: "Image",
    custom: { displayName: "Gallery Image", isSection: false },
    parent: "gallery-grid",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "gal-img-2": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=400&h=300&q=80",
      width: "300px",
      height: "200px",
      borderRadius: 8,
    },
    displayName: "Image",
    custom: { displayName: "Gallery Image", isSection: false },
    parent: "gallery-grid",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "gal-img-3": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=400&h=300&q=80",
      width: "300px",
      height: "200px",
      borderRadius: 8,
    },
    displayName: "Image",
    custom: { displayName: "Gallery Image", isSection: false },
    parent: "gallery-grid",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  services: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#f1f5f9",
      padding: "80px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 40,
    },
    displayName: "Section",
    custom: { displayName: "Services", componentType: "services", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["services-title", "services-grid"],
    linkedNodes: {},
  },
  "services-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Our Services",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "Services Title", isSection: false },
    parent: "services",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "services-grid": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 30,
      background: "transparent",
      padding: 0,
    },
    displayName: "Container",
    custom: { displayName: "Services Grid", isSection: false },
    parent: "services",
    hidden: false,
    nodes: ["service-1", "service-2", "service-3"],
    linkedNodes: {},
  },
  "service-1": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 30,
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 15,
      width: "300px",
    },
    displayName: "Container",
    custom: { displayName: "Service Card", isSection: false },
    parent: "services-grid",
    hidden: false,
    nodes: ["svc-1-title", "svc-1-desc"],
    linkedNodes: {},
  },
  "svc-1-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Web Design",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Service Title", isSection: false },
    parent: "service-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "svc-1-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "We create stunning designs that engage your audience.",
      fontSize: 14,
      color: "#64748b",
      lineHeight: 1.5,
    },
    displayName: "Text",
    custom: { displayName: "Service Description", isSection: false },
    parent: "service-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "service-2": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 30,
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 15,
      width: "300px",
    },
    displayName: "Container",
    custom: { displayName: "Service Card", isSection: false },
    parent: "services-grid",
    hidden: false,
    nodes: ["svc-2-title", "svc-2-desc"],
    linkedNodes: {},
  },
  "svc-2-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Development",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Service Title", isSection: false },
    parent: "service-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "svc-2-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Robust and scalable solutions using modern technologies.",
      fontSize: 14,
      color: "#64748b",
      lineHeight: 1.5,
    },
    displayName: "Text",
    custom: { displayName: "Service Description", isSection: false },
    parent: "service-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "service-3": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 30,
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 15,
      width: "300px",
    },
    displayName: "Container",
    custom: { displayName: "Service Card", isSection: false },
    parent: "services-grid",
    hidden: false,
    nodes: ["svc-3-title", "svc-3-desc"],
    linkedNodes: {},
  },
  "svc-3-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Marketing",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Service Title", isSection: false },
    parent: "service-3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "svc-3-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Strategies to grow your reach and increase conversions.",
      fontSize: 14,
      color: "#64748b",
      lineHeight: 1.5,
    },
    displayName: "Text",
    custom: { displayName: "Service Description", isSection: false },
    parent: "service-3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  features: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: "80px 20px",
      minHeight: "auto",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 48,
    },
    displayName: "Section",
    custom: {
      displayName: "Features Section",
      componentType: "features",
      isSection: true,
    },
    parent: "ROOT",
    hidden: false,
    nodes: ["features-title", "features-grid"],
    linkedNodes: {},
  },
  "features-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Key Features",
      fontSize: 36,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: {
      displayName: "Section Title",
      isSection: false,
    },
    parent: "features",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "features-grid": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "transparent",
      padding: 0,
      flexDirection: "row",
      alignItems: "stretch",
      justifyContent: "center",
      gap: 32,
      width: "100%",
    },
    displayName: "Container",
    custom: {
      displayName: "Features Grid",
      isSection: false,
    },
    parent: "features",
    hidden: false,
    nodes: ["feature-1", "feature-2", "feature-3"],
    linkedNodes: {},
  },
  "feature-1": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#f8fafc",
      padding: 32,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: 16,
      width: "300px",
    },
    displayName: "Container",
    custom: {
      displayName: "Feature Card",
      isSection: false,
    },
    parent: "features-grid",
    hidden: false,
    nodes: ["feature-1-title", "feature-1-desc"],
    linkedNodes: {},
  },
  "feature-1-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Easy to Use",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h3",
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Title",
      isSection: false,
    },
    parent: "feature-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-1-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Intuitive drag-and-drop interface that anyone can master in minutes.",
      fontSize: 14,
      fontWeight: 400,
      color: "#64748b",
      textAlign: "center",
      lineHeight: 1.6,
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Description",
      isSection: false,
    },
    parent: "feature-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-2": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#f8fafc",
      padding: 32,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: 16,
      width: "300px",
    },
    displayName: "Container",
    custom: {
      displayName: "Feature Card",
      isSection: false,
    },
    parent: "features-grid",
    hidden: false,
    nodes: ["feature-2-title", "feature-2-desc"],
    linkedNodes: {},
  },
  "feature-2-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Fully Responsive",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h3",
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Title",
      isSection: false,
    },
    parent: "feature-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-2-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Your website looks perfect on desktop, tablet, and mobile devices.",
      fontSize: 14,
      fontWeight: 400,
      color: "#64748b",
      textAlign: "center",
      lineHeight: 1.6,
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Description",
      isSection: false,
    },
    parent: "feature-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-3": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#f8fafc",
      padding: 32,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: 16,
      width: "300px",
    },
    displayName: "Container",
    custom: {
      displayName: "Feature Card",
      isSection: false,
    },
    parent: "features-grid",
    hidden: false,
    nodes: ["feature-3-title", "feature-3-desc"],
    linkedNodes: {},
  },
  "feature-3-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Lightning Fast",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h3",
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Title",
      isSection: false,
    },
    parent: "feature-3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-3-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Optimized performance ensures your site loads instantly every time.",
      fontSize: 14,
      fontWeight: 400,
      color: "#64748b",
      textAlign: "center",
      lineHeight: 1.6,
    },
    displayName: "Text",
    custom: {
      displayName: "Feature Description",
      isSection: false,
    },
    parent: "feature-3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  socials: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#1e293b",
      padding: "40px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 20,
    },
    displayName: "Section",
    custom: { displayName: "Social Media", componentType: "socials", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["socials-title", "socials-links"],
    linkedNodes: {},
  },
  "socials-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Follow Us",
      fontSize: 24,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: { displayName: "Socials Title", isSection: false },
    parent: "socials",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "socials-links": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 16,
      background: "transparent",
      padding: 0,
    },
    displayName: "Container",
    custom: { displayName: "Social Links", isSection: false },
    parent: "socials",
    hidden: false,
    nodes: ["soc-fb", "soc-tw", "soc-in"],
    linkedNodes: {},
  },
  "soc-fb": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "Facebook",
      background: "#3b5998",
      color: "#ffffff",
      padding: "10px 20px",
    },
    displayName: "Button",
    custom: { displayName: "Facebook Link", isSection: false },
    parent: "socials-links",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "soc-tw": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "Twitter",
      background: "#1da1f2",
      color: "#ffffff",
      padding: "10px 20px",
    },
    displayName: "Button",
    custom: { displayName: "Twitter Link", isSection: false },
    parent: "socials-links",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "soc-in": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "Instagram",
      background: "#e1306c",
      color: "#ffffff",
      padding: "10px 20px",
    },
    displayName: "Button",
    custom: { displayName: "Instagram Link", isSection: false },
    parent: "socials-links",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  newsletter: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#f8fafc",
      padding: "60px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 20,
    },
    displayName: "Section",
    custom: { displayName: "Newsletter", componentType: "newsletter", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["newsletter-title", "newsletter-form"],
    linkedNodes: {},
  },
  "newsletter-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Subscribe to Our Newsletter",
      fontSize: 28,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
    },
    displayName: "Text",
    custom: { displayName: "Newsletter Title", isSection: false },
    parent: "newsletter",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "newsletter-form": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 10,
      background: "transparent",
      padding: 0,
    },
    displayName: "Container",
    custom: { displayName: "Form Container", isSection: false },
    parent: "newsletter",
    hidden: false,
    nodes: ["newsletter-input", "newsletter-btn"],
    linkedNodes: {},
  },
  "newsletter-input": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Enter your email...",
      fontSize: 16,
      color: "#94a3b8",
      textAlign: "left",
      // Simulating input visual
      // In a real scenario, this would be an Input component
    },
    displayName: "Text",
    custom: { displayName: "Input Placeholder", isSection: false },
    parent: "newsletter-form",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "newsletter-btn": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "Subscribe",
      background: "#0f172a",
      color: "#ffffff",
    },
    displayName: "Button",
    custom: { displayName: "Subscribe Button", isSection: false },
    parent: "newsletter-form",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  testimonials: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: "80px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 40,
    },
    displayName: "Section",
    custom: { displayName: "Testimonials", componentType: "testimonials", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["test-title", "test-grid"],
    linkedNodes: {},
  },
  "test-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "What Our Clients Say",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "Testimonials Title", isSection: false },
    parent: "testimonials",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "test-grid": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 30,
      background: "transparent",
      padding: 0,
    },
    displayName: "Container",
    custom: { displayName: "Testimonials Grid", isSection: false },
    parent: "testimonials",
    hidden: false,
    nodes: ["test-1", "test-2"],
    linkedNodes: {},
  },
  "test-1": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#f8fafc",
      padding: 24,
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 12,
      width: "300px",
    },
    displayName: "Container",
    custom: { displayName: "Testimonial Card", isSection: false },
    parent: "test-grid",
    hidden: false,
    nodes: ["test-1-quote", "test-1-auth"],
    linkedNodes: {},
  },
  "test-1-quote": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "\"Amazing service! Highly recommended.\"",
      fontSize: 16,
      color: "#475569",
      lineHeight: 1.6,
      textAlign: "left",
    },
    displayName: "Text",
    custom: { displayName: "Quote", isSection: false },
    parent: "test-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "test-1-auth": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "- Alex Johnson",
      fontSize: 14,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Author", isSection: false },
    parent: "test-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "test-2": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#f8fafc",
      padding: 24,
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 12,
      width: "300px",
    },
    displayName: "Container",
    custom: { displayName: "Testimonial Card", isSection: false },
    parent: "test-2",
    hidden: false,
    nodes: ["test-2-quote", "test-2-auth"],
    linkedNodes: {},
  },
  "test-2-quote": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "\"The best decision we made for our business.\"",
      fontSize: 16,
      color: "#475569",
      lineHeight: 1.6,
      textAlign: "left",
    },
    displayName: "Text",
    custom: { displayName: "Quote", isSection: false },
    parent: "test-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "test-2-auth": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "- Sarah Williams",
      fontSize: 14,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Author", isSection: false },
    parent: "test-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  casestudies: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: "80px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 40,
    },
    displayName: "Section",
    custom: { displayName: "Case Studies", componentType: "case studies", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["cs-title", "cs-grid"],
    linkedNodes: {},
  },
  "cs-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Recent Case Studies",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "Case Studies Title", isSection: false },
    parent: "casestudies",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "cs-grid": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 30,
      background: "transparent",
      padding: 0,
    },
    displayName: "Container",
    custom: { displayName: "Case Studies Grid", isSection: false },
    parent: "casestudies",
    hidden: false,
    nodes: ["cs-1", "cs-2"],
    linkedNodes: {},
  },
  "cs-1": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 20,
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 12,
      width: "350px",
    },
    displayName: "Container",
    custom: { displayName: "Case Study Card", isSection: false },
    parent: "cs-grid",
    hidden: false,
    nodes: ["cs-1-img", "cs-1-title", "cs-1-desc"],
    linkedNodes: {},
  },
  "cs-1-img": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&h=400&q=80",
      width: "100%",
      height: "200px",
      borderRadius: 8,
    },
    displayName: "Image",
    custom: { displayName: "CS Image", isSection: false },
    parent: "cs-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "cs-1-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Tech Corp Rebranding",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "CS Title", isSection: false },
    parent: "cs-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "cs-1-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "A complete overhaul of brand identity resulting in 50% more engagement.",
      fontSize: 14,
      color: "#64748b",
      lineHeight: 1.5,
    },
    displayName: "Text",
    custom: { displayName: "CS Desc", isSection: false },
    parent: "cs-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "cs-2": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 20,
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 12,
      width: "350px",
    },
    displayName: "Container",
    custom: { displayName: "Case Study Card", isSection: false },
    parent: "cs-grid",
    hidden: false,
    nodes: ["cs-2-img", "cs-2-title", "cs-2-desc"],
    linkedNodes: {},
  },
  "cs-2-img": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1551288049-bbbda5366392?auto=format&fit=crop&w=600&h=400&q=80",
      width: "100%",
      height: "200px",
      borderRadius: 8,
    },
    displayName: "Image",
    custom: { displayName: "CS Image", isSection: false },
    parent: "cs-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "cs-2-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "E-commerce Growth",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "CS Title", isSection: false },
    parent: "cs-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "cs-2-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Strategic marketing campaign that doubled sales in 3 months.",
      fontSize: 14,
      color: "#64748b",
      lineHeight: 1.5,
    },
    displayName: "Text",
    custom: { displayName: "CS Desc", isSection: false },
    parent: "cs-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  whyjoinus: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#f1f5f9",
      padding: "80px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 30,
    },
    displayName: "Section",
    custom: { displayName: "Why Join Us", componentType: "why join us", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["wju-title", "wju-content"],
    linkedNodes: {},
  },
  "wju-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Why Join Our Team?",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "WJU Title", isSection: false },
    parent: "whyjoinus",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "wju-content": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "We offer competitive salaries, flexible work hours, and a supportive environment where you can grow.",
      fontSize: 18,
      color: "#475569",
      textAlign: "center",
      lineHeight: 1.6,
      maxWidth: "800px",
    },
    displayName: "Text",
    custom: { displayName: "WJU Content", isSection: false },
    parent: "whyjoinus",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  privacypolicy: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: "60px 20px",
      maxWidth: "1000px",
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 20,
    },
    displayName: "Section",
    custom: { displayName: "Privacy Policy", componentType: "privacy policy", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["pp-title", "pp-text"],
    linkedNodes: {},
  },
  "pp-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Privacy Policy",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "left",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "PP Title", isSection: false },
    parent: "privacypolicy",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "pp-text": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Your privacy is important to us. This policy outlines how we collect, use, and protect your data...",
      fontSize: 16,
      color: "#475569",
      lineHeight: 1.8,
      textAlign: "left",
    },
    displayName: "Text",
    custom: { displayName: "PP Text", isSection: false },
    parent: "privacypolicy",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  pricing: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#f8fafc",
      padding: "80px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 40,
    },
    displayName: "Section",
    custom: { displayName: "Pricing", componentType: "pricing", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["pricing-title", "pricing-grid"],
    linkedNodes: {},
  },
  "pricing-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Our Pricing Plans",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "Pricing Title", isSection: false },
    parent: "pricing",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "pricing-grid": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 30,
      background: "transparent",
      padding: 0,
    },
    displayName: "Container",
    custom: { displayName: "Pricing Grid", isSection: false },
    parent: "pricing",
    hidden: false,
    nodes: ["plan-1", "plan-2"],
    linkedNodes: {},
  },
  "plan-1": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 30,
      flexDirection: "column",
      alignItems: "center",
      gap: 20,
      width: "300px",
    },
    displayName: "Container",
    custom: { displayName: "Basic Plan", isSection: false },
    parent: "pricing-grid",
    hidden: false,
    nodes: ["plan-1-name", "plan-1-price", "plan-1-btn"],
    linkedNodes: {},
  },
  "plan-1-name": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Basic",
      fontSize: 24,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Plan Name", isSection: false },
    parent: "plan-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "plan-1-price": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "$19/mo",
      fontSize: 36,
      fontWeight: 700,
      color: "#3b82f6",
    },
    displayName: "Text",
    custom: { displayName: "Plan Price", isSection: false },
    parent: "plan-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "plan-1-btn": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "Choose Plan",
      background: "#f1f5f9",
      color: "#1e293b",
    },
    displayName: "Button",
    custom: { displayName: "Plan Button", isSection: false },
    parent: "plan-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "plan-2": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 30,
      flexDirection: "column",
      alignItems: "center",
      gap: 20,
      width: "300px",
    },
    displayName: "Container",
    custom: { displayName: "Pro Plan", isSection: false },
    parent: "pricing-grid",
    hidden: false,
    nodes: ["plan-2-name", "plan-2-price", "plan-2-btn"],
    linkedNodes: {},
  },
  "plan-2-name": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Professional",
      fontSize: 24,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Plan Name", isSection: false },
    parent: "plan-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "plan-2-price": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "$49/mo",
      fontSize: 36,
      fontWeight: 700,
      color: "#3b82f6",
    },
    displayName: "Text",
    custom: { displayName: "Plan Price", isSection: false },
    parent: "plan-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "plan-2-btn": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "Choose Plan",
      background: "#3b82f6",
      color: "#ffffff",
    },
    displayName: "Button",
    custom: { displayName: "Plan Button", isSection: false },
    parent: "plan-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  termsofservice: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: "60px 20px",
      maxWidth: "1000px",
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 20,
    },
    displayName: "Section",
    custom: { displayName: "Terms of Service", componentType: "terms of service", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["tos-title", "tos-text"],
    linkedNodes: {},
  },
  "tos-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Terms of Service",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "left",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "ToS Title", isSection: false },
    parent: "termsofservice",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "tos-text": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "By using our service, you agree to the following terms and conditions...",
      fontSize: 16,
      color: "#475569",
      lineHeight: 1.8,
      textAlign: "left",
    },
    displayName: "Text",
    custom: { displayName: "ToS Text", isSection: false },
    parent: "termsofservice",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  resources: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#f1f5f9",
      padding: "80px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 30,
    },
    displayName: "Section",
    custom: { displayName: "Resources", componentType: "resources", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["res-title", "res-grid"],
    linkedNodes: {},
  },
  "res-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Helpful Resources",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "Resources Title", isSection: false },
    parent: "resources",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "res-grid": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 30,
      background: "transparent",
      padding: 0,
    },
    displayName: "Container",
    custom: { displayName: "Resources Grid", isSection: false },
    parent: "resources",
    hidden: false,
    nodes: ["res-1", "res-2"],
    linkedNodes: {},
  },
  "res-1": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "Documentation",
      background: "#ffffff",
      color: "#3b82f6",
      padding: "20px 40px",
      border: "1px solid #e2e8f0",
    },
    displayName: "Button",
    custom: { displayName: "Resource Link", isSection: false },
    parent: "res-grid",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "res-2": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "API Reference",
      background: "#ffffff",
      color: "#3b82f6",
      padding: "20px 40px",
      border: "1px solid #e2e8f0",
    },
    displayName: "Button",
    custom: { displayName: "Resource Link", isSection: false },
    parent: "res-grid",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  contact: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: "80px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 40,
    },
    displayName: "Section",
    custom: { displayName: "Contact Us", componentType: "contact", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["contact-title", "contact-content"],
    linkedNodes: {},
  },
  "contact-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Get in Touch",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "Contact Title", isSection: false },
    parent: "contact",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "contact-content": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 40,
      background: "transparent",
      padding: 0,
      alignItems: "flex-start",
    },
    displayName: "Container",
    custom: { displayName: "Contact Content", isSection: false },
    parent: "contact",
    hidden: false,
    nodes: ["contact-info", "contact-map"],
    linkedNodes: {},
  },
  "contact-info": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "column",
      gap: 20,
      background: "transparent",
      padding: 0,
      width: "400px",
    },
    displayName: "Container",
    custom: { displayName: "Info Column", isSection: false },
    parent: "contact-content",
    hidden: false,
    nodes: ["ci-email", "ci-phone"],
    linkedNodes: {},
  },
  "ci-email": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Email: hello@company.com",
      fontSize: 18,
      color: "#475569",
    },
    displayName: "Text",
    custom: { displayName: "Email", isSection: false },
    parent: "contact-info",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "ci-phone": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Phone: +1 (555) 123-4567",
      fontSize: 18,
      color: "#475569",
    },
    displayName: "Text",
    custom: { displayName: "Phone", isSection: false },
    parent: "contact-info",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "contact-map": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=600&h=400&q=80",
      width: "400px",
      height: "300px",
      borderRadius: 8,
    },
    displayName: "Image",
    custom: { displayName: "Map Placeholder", isSection: false },
    parent: "contact-content",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  faq: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#f8fafc",
      padding: "80px 20px",
      maxWidth: "1000px",
      flexDirection: "column",
      alignItems: "center",
      gap: 30,
    },
    displayName: "Section",
    custom: { displayName: "FAQ", componentType: "faq", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["faq-title", "faq-list"],
    linkedNodes: {},
  },
  "faq-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Frequently Asked Questions",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "FAQ Title", isSection: false },
    parent: "faq",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "faq-list": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "column",
      gap: 20,
      background: "transparent",
      padding: 0,
      width: "100%",
    },
    displayName: "Container",
    custom: { displayName: "Question List", isSection: false },
    parent: "faq",
    hidden: false,
    nodes: ["faq-1", "faq-2"],
    linkedNodes: {},
  },
  "faq-1": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 20,
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 10,
      width: "100%",
    },
    displayName: "Container",
    custom: { displayName: "Question Item", isSection: false },
    parent: "faq-list",
    hidden: false,
    nodes: ["faq-1-q", "faq-1-a"],
    linkedNodes: {},
  },
  "faq-1-q": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "How do I get started?",
      fontSize: 18,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Question", isSection: false },
    parent: "faq-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "faq-1-a": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Simply sign up for an account and follow the onboarding steps.",
      fontSize: 16,
      color: "#475569",
    },
    displayName: "Text",
    custom: { displayName: "Answer", isSection: false },
    parent: "faq-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "faq-2": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 20,
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 10,
      width: "100%",
    },
    displayName: "Container",
    custom: { displayName: "Question Item", isSection: false },
    parent: "faq-list",
    hidden: false,
    nodes: ["faq-2-q", "faq-2-a"],
    linkedNodes: {},
  },
  "faq-2-q": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Can I cancel anytime?",
      fontSize: 18,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Question", isSection: false },
    parent: "faq-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "faq-2-a": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Yes, you can cancel your subscription at any time without penalty.",
      fontSize: 16,
      color: "#475569",
    },
    displayName: "Text",
    custom: { displayName: "Answer", isSection: false },
    parent: "faq-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  blogs: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: "80px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 40,
    },
    displayName: "Section",
    custom: { displayName: "Latest Blogs", componentType: "blogs", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["blogs-title", "blogs-grid"],
    linkedNodes: {},
  },
  "blogs-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Latest News",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "Blogs Title", isSection: false },
    parent: "blogs",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "blogs-grid": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 30,
      background: "transparent",
      padding: 0,
    },
    displayName: "Container",
    custom: { displayName: "Blogs Grid", isSection: false },
    parent: "blogs",
    hidden: false,
    nodes: ["blog-1", "blog-2"],
    linkedNodes: {},
  },
  "blog-1": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 0,
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 15,
      width: "350px",
    },
    displayName: "Container",
    custom: { displayName: "Blog Card", isSection: false },
    parent: "blogs-grid",
    hidden: false,
    nodes: ["blog-1-img", "blog-1-content"],
    linkedNodes: {},
  },
  "blog-1-img": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1581291518633-83b4ebd19d83e?auto=format&fit=crop&w=600&h=400&q=80",
      width: "100%",
      height: "200px",
      borderRadius: 8,
    },
    displayName: "Image",
    custom: { displayName: "Blog Image", isSection: false },
    parent: "blog-1",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "blog-1-content": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      padding: 10,
      flexDirection: "column",
      gap: 10,
      background: "transparent",
    },
    displayName: "Container",
    custom: { displayName: "Content Wrapper", isSection: false },
    parent: "blog-1",
    hidden: false,
    nodes: ["blog-1-title", "blog-1-excerpt"],
    linkedNodes: {},
  },
  "blog-1-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "The Future of Web Design",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Blog Title", isSection: false },
    parent: "blog-1-content",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "blog-1-excerpt": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Discover the trends that will shape the internet in 2026...",
      fontSize: 14,
      color: "#64748b",
      lineHeight: 1.5,
    },
    displayName: "Text",
    custom: { displayName: "Blog Excerpt", isSection: false },
    parent: "blog-1-content",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "blog-2": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 0,
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 15,
      width: "350px",
    },
    displayName: "Container",
    custom: { displayName: "Blog Card", isSection: false },
    parent: "blogs-grid",
    hidden: false,
    nodes: ["blog-2-img", "blog-2-content"],
    linkedNodes: {},
  },
  "blog-2-img": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&h=400&q=80",
      width: "100%",
      height: "200px",
      borderRadius: 8,
    },
    displayName: "Image",
    custom: { displayName: "Blog Image", isSection: false },
    parent: "blog-2",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "blog-2-content": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      padding: 10,
      flexDirection: "column",
      gap: 10,
      background: "transparent",
    },
    displayName: "Container",
    custom: { displayName: "Content Wrapper", isSection: false },
    parent: "blog-2",
    hidden: false,
    nodes: ["blog-2-title", "blog-2-excerpt"],
    linkedNodes: {},
  },
  "blog-2-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Maximizing SEO",
      fontSize: 20,
      fontWeight: 600,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Blog Title", isSection: false },
    parent: "blog-2-content",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "blog-2-excerpt": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Tips and tricks to get your website ranked #1 on Google...",
      fontSize: 14,
      color: "#64748b",
      lineHeight: 1.5,
    },
    displayName: "Text",
    custom: { displayName: "Blog Excerpt", isSection: false },
    parent: "blog-2-content",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  product: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#f8fafc",
      padding: "80px 20px",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      gap: 40,
    },
    displayName: "Section",
    custom: { displayName: "Featured Product", componentType: "product", isSection: true },
    parent: "ROOT",
    hidden: false,
    nodes: ["prod-title", "prod-content"],
    linkedNodes: {},
  },
  "prod-title": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Product Spotlight",
      fontSize: 32,
      fontWeight: 700,
      color: "#1e293b",
      textAlign: "center",
      tagName: "h2",
    },
    displayName: "Text",
    custom: { displayName: "Product Title", isSection: false },
    parent: "product",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "prod-content": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 40,
      background: "transparent",
      padding: 0,
      alignItems: "center",
    },
    displayName: "Container",
    custom: { displayName: "Product Content", isSection: false },
    parent: "product",
    hidden: false,
    nodes: ["prod-img", "prod-details"],
    linkedNodes: {},
  },
  "prod-img": {
    type: { resolvedName: "Image" },
    isCanvas: false,
    props: {
      src: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&h=600&q=80",
      width: "400px",
      height: "400px",
      borderRadius: 8,
    },
    displayName: "Image",
    custom: { displayName: "Product Image", isSection: false },
    parent: "prod-content",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "prod-details": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      flexDirection: "column",
      gap: 20,
      background: "transparent",
      padding: 0,
      width: "400px",
      alignItems: "flex-start",
    },
    displayName: "Container",
    custom: { displayName: "Details Column", isSection: false },
    parent: "prod-content",
    hidden: false,
    nodes: ["prod-name", "prod-price", "prod-desc", "prod-btn"],
    linkedNodes: {},
  },
  "prod-name": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Smart Watch Series X",
      fontSize: 28,
      fontWeight: 700,
      color: "#1e293b",
    },
    displayName: "Text",
    custom: { displayName: "Product Name", isSection: false },
    parent: "prod-details",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "prod-price": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "$299.99",
      fontSize: 24,
      fontWeight: 600,
      color: "#3b82f6",
    },
    displayName: "Text",
    custom: { displayName: "Product Price", isSection: false },
    parent: "prod-details",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "prod-desc": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "The ultimate companion for your active lifestyle. Features include heart rate monitoring, GPS, and 5-day battery life.",
      fontSize: 16,
      color: "#475569",
      lineHeight: 1.6,
    },
    displayName: "Text",
    custom: { displayName: "Product Desc", isSection: false },
    parent: "prod-details",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "prod-btn": {
    type: { resolvedName: "Button" },
    isCanvas: false,
    props: {
      text: "Add to Cart",
      background: "#1e293b",
      color: "#ffffff",
      padding: "16px 32px",
    },
    displayName: "Button",
    custom: { displayName: "Buy Button", isSection: false },
    parent: "prod-details",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  footer: {
    type: { resolvedName: "Section" },
    isCanvas: true,
    props: {
      background: "#0f172a",
      padding: "40px 20px",
      minHeight: "auto",
      maxWidth: "1200px",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 16,
    },
    displayName: "Section",
    custom: {
      displayName: "Footer",
      componentType: "footer",
      isSection: true,
    },
    parent: "ROOT",
    hidden: false,
    nodes: ["footer-text", "footer-copyright"],
    linkedNodes: {},
  },
  "footer-text": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Logo",
      fontSize: 20,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Footer Logo",
      isSection: false,
    },
    parent: "footer",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "footer-copyright": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "© 2026 Your Brand. All rights reserved.",
      fontSize: 14,
      fontWeight: 400,
      color: "rgba(255,255,255,0.6)",
      textAlign: "center",
    },
    displayName: "Text",
    custom: {
      displayName: "Copyright",
      isSection: false,
    },
    parent: "footer",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};

// Helper function to get the template as a serialized string
export const getSerializedTemplate = () => JSON.stringify(defaultTemplate);
